# -*- coding: utf-8 -*-
"""Products api.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17qQg9oYzHmN34-AJ_2NaHh2_LJQelg-l
"""

import json
import random
from faker import Faker
import csv

faker = Faker()

# Constants
NUM_PRODUCTS = 850
NUM_BRANDS = 50
STYLE_TO_MATERIALS = {
    "casual": ["cotton", "denim", "canvas", "polyester", "synthetic"],
    "formal": ["silk", "wool", "leather", "metal"],
    "sporty": ["polyester", "synthetic", "rubber", "canvas"],
    "trendy": ["leather", "silk", "metal", "linen"],
    "vintage": ["cotton", "wool", "linen", "silk"]
}
STYLE_TAGS = list(STYLE_TO_MATERIALS.keys())
SEASONS = ["spring", "summer", "autumn", "winter", "all"]
SUSTAINABILITY_TAGS = ["organic cotton", "recycled polyester", "vegan leather", "none"]

REVIEW_COMMENTS_LOW = [
    "Fabric is scratchy and uncomfortable.",
    "Poor quality stitching, came undone quickly.",
    "Faded after just one wash.",
    "Sizing is way off—runs too small.",
    "Not as described, very misleading!",
    "Feels cheap, definitely not worth the price.",
    "Buttons popped off within a few wears.",
    "Material feels flimsy and weak.",
    "Color looked different online.",
    "Too stiff and awkward to wear.",
    "Started pilling after a couple of uses.",
    "Didn't match the advertised texture.",
    "Way overpriced for what you get.",
    "Seams already unraveling.",
    "Shrunk even after following washing instructions.",
    "The fit is completely wrong.",
    "Not breathable—makes me sweaty.",
    "Too thin and see-through.",
    "Broke within days, terrible durability.",
    "Smelled weird out of the package.",
    "Doesn’t hold its shape after wearing.",
    "Returned immediately—such a disappointment.",
    "Painful to wear, not comfortable at all.",
    "Arrived with stains and damage.",
    "Expected much better at this price point.",
    "Poorly made, doesn’t look premium.",
    "Fabric tore after just a few wears.",
    "Not suitable for the season it's advertised for.",
    "Weirdly cut, doesn’t sit right on the body.",
    "Started fraying almost immediately.",
    "Zipper broke after one use.",
    "Way thinner than expected, feels flimsy.",
    "Came with loose threads everywhere.",
    "Rough material, not skin-friendly.",
    "Looks cheap despite the price tag.",
    "Sleeves are too tight, uncomfortable.",
    "Would never buy from this brand again.",
    "Gets wrinkled too fast, hard to maintain.",
    "Didn’t last even a month.",
    "Awkward fit around the shoulders.",
    "Really disappointed with this purchase.",
    "Scratchy fabric—irritates my skin.",
    "Shipping took way too long.",
    "The material looks like it would fall apart.",
    "Doesn’t look anything like the pictures.",
    "No stretch, very restrictive.",
    "I wish I had read the reviews before buying!",
    "Not worth the hassle of returning.",
    "Arrived late and wasn’t worth the wait."
]


REVIEW_COMMENTS_HIGH = [
    "Absolutely love this purchase!",
    "Soft, cozy, and great quality.",
    "Perfect fit—feels tailored!",
    "Matches the description perfectly.",
    "Great craftsmanship—worth every cent.",
    "Super stylish and flattering.",
    "Fabric feels premium and durable.",
    "Color is vibrant and beautiful.",
    "Wearing it feels amazing!",
    "Would definitely buy again.",
    "Fits exactly as expected—true to size!",
    "My new favorite item!",
    "Highly impressed by the material.",
    "Holds up great in the wash.",
    "Keeps its shape even after multiple wears.",
    "Received a ton of compliments on this.",
    "Perfect for any occasion!",
    "Great attention to detail.",
    "Lightweight but super warm!",
    "Breathable and easy to style.",
    "Excellent price for such high quality.",
    "Definitely exceeded my expectations!",
    "The texture is just amazing!",
    "So comfortable I could wear it daily!",
    "Ideal for layering, very versatile.",
    "Such a fantastic purchase!",
    "Really well-made, feels luxurious.",
    "Beautifully crafted, worth every penny.",
    "Very impressed with this brand!",
    "Elegant and classy yet casual enough.",
    "The fit is absolutely perfect!",
    "Great buy, highly recommend!",
    "Love how soft and comfortable it is!",
    "Fantastic quality for the price.",
    "Super breathable fabric, perfect for summer.",
    "Already planning to buy another one!",
    "Perfect gift item—my friend loved it!",
    "Lightweight yet warm, great balance.",
    "Exactly what I was looking for!",
    "Extremely stylish and trendy!",
    "Softest fabric I’ve ever owned.",
    "Perfect for travel—packs easily!",
    "I wear this all the time now.",
    "Unbelievable quality for such a great price!",
    "Fabric feels luxurious to the touch.",
    "Really happy with my purchase.",
    "Holds up really well over time.",
    "Quick delivery and excellent packaging.",
    "Great product, would buy again!",
    "My go-to item now, love it!"
]
def load_styles(file_path):
    styles_list = []
    with open(file_path, "r", encoding="utf-8") as f:
        reader = csv.reader(f)
        for row in reader:
            if len(row) < 10 or not row[0].isdigit():
                continue
            styles_list.append({
                "id": int(row[0]),
                "gender": row[1].strip(),
                "masterCategory": row[2].strip(),
                "subCategory": row[3].strip(),
                "articleType": row[4].strip(),
                "baseColour": row[5].strip(),
                "season": row[6].strip().lower(),
                "year": row[7].strip(),
                "usage": row[8].strip(),
                "productDisplayName": row[9].strip(),
            })
    return styles_list

def load_images(file_path):
    with open(file_path, "r", encoding="utf-8") as f:
        return [line.strip() for line in f if line.strip()]

def generate_manager():
    first = faker.first_name()
    last = faker.last_name()
    return {
        "firstName": first,
        "lastName": last,
        "email": f"{first.lower()}.{last.lower()}{random.randint(1, 99)}@gmail.com"
    }

def generate_stockist(store_id):
    return {
        "storeId": store_id,
        "storeName": faker.company(),
        "price": round(random.uniform(20, 200), 2),
        "stock": random.randint(1, 50),
        "manager": generate_manager()
    }

def generate_review():
    first = faker.first_name()
    last = faker.last_name()
    rating = random.randint(1, 5)
    comment_pool = REVIEW_COMMENTS_LOW if rating <= 2 else REVIEW_COMMENTS_HIGH
    return {
        "firstName": first,
        "lastName": last,
        "email": f"{first.lower()}.{last.lower()}{random.randint(1, 99)}@gmail.com",
        "rating": rating,
        "comment": random.choice(comment_pool),
        "date": str(faker.date_this_year())
    }

def get_sustainability_tag(material):
    if "cotton" in material:
        return "organic cotton"
    elif "polyester" in material:
        return "recycled polyester"
    elif "leather" in material:
        return "vegan leather"
    else:
        return "none"

def pick_consistent_seasons():
    return random.choice([("spring", "summer"), ("autumn", "winter"), ("all", "all")])

def generate_product(i, brand, store_id_start, images_list, styles_list):
    use_meta = i < len(styles_list)
    if use_meta:
        meta = styles_list[i]
        category = meta["articleType"]
        color = meta["baseColour"]
        season = [meta["season"]] if meta["season"] in SEASONS else ["all"]
        product_name = meta["productDisplayName"]
        gender = meta["gender"]
    else:
        category = random.choice(["tops", "bottoms", "accessories", "shoes"])
        color = faker.color_name()
        season = list(pick_consistent_seasons())
        product_name = f"{random.choice(['Classic', 'Modern', 'Elegant'])} {category.capitalize()}"
        gender = random.choice(["Men", "Women", "Unisex"])

    style_tags = random.sample(STYLE_TAGS, 2)
    possible_materials = list({material for tag in style_tags for material in STYLE_TO_MATERIALS.get(tag, [])})
    material = random.choice(possible_materials) if possible_materials else "cotton"
    description = f"This {material} item is a great addition to your {season[0]} wardrobe — perfect for {style_tags[0]} looks."
    sustainability = get_sustainability_tag(material)
    image_url = images_list[i % len(images_list)] if images_list else None

    return {
        "productId": i + 1,
        "name": product_name,
        "description": description,
        "category": category,
        "brand": brand,
        "color": color,
        "material": material,
        "gender": gender,
        "styleTags": style_tags,
        "season": season,
        "sustainability": sustainability,
        "image": image_url.split(",")[1] if image_url and "," in image_url else None,
        "currency": "USD",
        "stockists": [generate_stockist(store_id_start + j) for j in range(random.randint(10, 15))],
        "reviews": [generate_review() for _ in range(random.randint(2, 5))]
    }

def main():
    styles_file = "styles.txt"
    images_file = "images.txt"
    output_file = "productsApi.json"

    styles_list = load_styles(styles_file)
    

    brands = [{
        "brandId": i + 1,
        "name": faker.unique.company(),
        "origin": faker.country()
    } for i in range(NUM_BRANDS)]

    products = []
    store_id_start = 1000
    for i in range(NUM_PRODUCTS):
        brand = random.choice(brands)
        product = generate_product(i, brand, store_id_start, images_list, styles_list)
        products.append(product)
        store_id_start += 20

    output_data = {
        "brands": brands,
        "products": products
    }

    with open(output_file, "w", encoding="utf-8") as f:
        json.dump(output_data, f, indent=2)


if __name__ == "__main__":
    main()

